[versions]
# libraries
junit = "4.13.2"
opentest4j = "1.3.0"
sentry = "8.31.0"
commonsText = "1.15.0"
clikt = "5.0.3"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.11.0"
kotlin = "2.3.0"
grammarkit = "2023.3.0.1"
download = "5.6.0"
kover = "0.9.5"
qodana = "2025.3.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
sentry = { group = "io.sentry", name = "sentry", version.ref = "sentry" }
commonsText = { group = "org.apache.commons", name = "commons-text", version.ref = "commonsText" }
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "clikt" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
grammarkit = { id = "org.jetbrains.grammarkit", version.ref = "grammarkit" }
download = { id = "de.undercouch.download", version.ref = "download" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
